name: geo_env_simple
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - backcall=0.1.0
  - bleach=3.1.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - contextily=1.0rc2
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - deprecated=1.2.7
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.13
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=3.0.2
  - geographiclib=1.50
  - geopandas=0.6.2
  - geoplot=0.4.0
  - geopy=1.20.0
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.2.0
  - ipykernel=5.1.3
  - ipython=7.10.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=3.0.2
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - llvm-openmp=9.0.0
  - lz4-c=1.8.3
  - mapclassify=2.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mercantile=1.1.2
  - mistune=0.8.4
  - more-itertools=8.0.2
  - munch=2.5.0
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.3
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - owslib=0.19.0
  - pandas=0.25.3
  - pandoc=2.8.1
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - proj=6.2.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygments=2.5.2
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyproj=2.4.2.post1
  - pyrsistent=0.15.6
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - rasterio=1.1.1
  - readline=8.0
  - requests=2.22.0
  - rtree=0.9.3
  - scikit-learn=0.22
  - scipy=1.3.2
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=42.0.2
  - shapely=1.6.4
  - six=1.13.0
  - snuggs=1.4.7
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xerces-c=3.2.2
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
